---
name: "Webhooks"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "3.1.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Webhooks. Flexible and robust"
description: >
  Supports couple of webhook types including Plex one.
category: "General"
owner: "shemanaev"
artifacts:
  - "Jellyfin.Webhooks.dll"
changelog: >
  Add new event types
