---
name: "Webhooks"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.0.1"
targetAbi: "10.6.0.0"
overview: "Webhooks. Flexible and robust"
description: >
  Supports couple of webhook types including Plex one.
category: "General"
owner: "shemanaev"
artifacts:
  - "Jellyfin.Webhooks.dll"
changelog: >
  Updated for 10.6
