---
name: "Webhooks"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "3.8.0.0"
targetAbi: "10.10.3.0"
framework: "net8.0"
overview: "Webhooks. Flexible and robust"
description: >
  Supports couple of webhook types including Plex one.
category: "General"
owner: "shemanaev"
artifacts:
  - "Jellyfin.Webhooks.dll"
changelog: >
  Jellyfin 10.10 compatibility
